AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Aggregate Sag Lambda og Gateway
Parameters:
  Stage:
    Type: String
Resources:
#  AggregateSagFunctionPermission:
#    Type: AWS::Lambda::Permission
#    DependsOn:
#      - AggregateSagFunction
#      - ApiGatewayApi
#    Properties:
#      Action: lambda:InvokeFunction
#      FunctionName: !Ref AggregateSagFunction
#      Principal: apigateway.amazonaws.com

  AggregateSagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aggregate_sag_lambda.aggregate_sag
      Runtime: java8
      CodeUri: target/aggregate-sag-lambda-0.3.1-standalone.jar
      MemorySize: 1024
      Role: arn:aws:iam::593176282530:role/lambda-s3-execution-role
      Timeout: 20
      Tracing: Active
      AutoPublishAlias: !Ref Stage
#      Events:
#        PutEvents:
#          Type: Api
#          Properties:
#            RestApiId: !Ref ApiGatewayApi
#            Path: /aggregate-sag
#            Method: put

#Outputs:
#  ApiUrl:
#    Description: URL of your API endpoint
#    Value: !Join
#      - ''
#      - - https://
#        - !Ref ApiGatewayApi
#        - '.execute-api.'
#        - !Ref 'AWS::Region'
#        - '.amazonaws.com/local'
